# Generated by Django 3.2.4 on 2021-06-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_hallbooking_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='hallbooking',
            name='end_timeing',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='hallbooking',
            name='start_timeing',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='hallbooking',
            name='booking_date',
            field=models.DateField(null=True),
        ),
    ]
