# Generated by Django 3.2.4 on 2021-06-21 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_hallbooking_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hallbooking',
            name='day',
        ),
    ]
